import { faComment, faEyeSlash, faStar, faTimesCircle, faUser } from '@fortawesome/free-regular-svg-icons';
import {
    // faComment,
    // faFlask,
    // faWeight,
    // faWalking,
    // faUtensils,
    // faToilet,
    // faPills,
    // faSpa,
    // faGripLines,
    // faPlus,
    // faUserNurse,
    // faHandHoldingHeart,
    // faViruses,
    // faArrowCircleUp,
    // faArrowCircleDown,
    // faCamera,
    // faTint,
    // faMinus,
    faArrowLeft,
    // faShoppingCart,
    // faEgg,
    // faCarrot,
    // faWater,
    faArrowRight,
    // faMapMarkedAlt,
    // faCircle,
    // faBan,
    // faBreadSlice,
    // faTrash,
    faEye,
    // faPaperPlane,
    faVideo,
    // faBookReader,
    // faMale,
    // faCaretDown,
    // faTimes,
    faHome,
    faUserCog,
    faHistory,
    faCalendarAlt,
    faAngleRight,
    faMicrophone,
    faMicrophoneSlash,
    faVideoSlash,
    faShare,
    faSignOutAlt,
    faKey,
    faAngleDown,
    faCircle,
} from '@fortawesome/free-solid-svg-icons';

const icons:any ={
    'Home': faHome,
    'Settings': faUserCog,
    'History': faHistory,
    'Schedule': faCalendarAlt,
    'Cross': faTimesCircle,
    'User': faUser,
    'Forward': faArrowRight,
    'RightTriangle': faAngleRight,
    'Video': faVideo,
    'VideoOff': faVideoSlash,
    'BackArrow': faArrowLeft,
    'MicOn': faMicrophone,
    'MicOff': faMicrophoneSlash,
    'Chat':faComment,
    'Eye': faEye,
    'CloseEye': faEyeSlash,
    'Star':faStar,
    'Share': faShare,
    'Logout': faSignOutAlt,
    'Key': faKey,
    'Triangle':faAngleDown,
    'Circle':faCircle

}
export default icons;